version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - VIRTUAL_HOST=jellyfin.rc-t.online
      - VIRTUAL_PORT=8096
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /data-docker/jellyfin/:/config
      - /medias/tv:/data/tvshows
      - /medias/movies:/data/movies
    devices:
      - /dev/dri:/dev/dri
    networks:
          - nginx_nginx_net        
    restart: unless-stopped
    
networks:
  nginx_nginx_net:
    external: true