version: "3"
services: 

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment: 
      - TZ=Europe/Paris
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 5 4 * * *
      - WATCHTOWER_LABEL_ENABLE=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
