version: "3"
services: 

  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - VIRTUAL_HOST=rc-t.online
      - VIRTUAL_PORT=80
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /data-docker/heimdall/config/:/config
      - /data-docker/heimdall/public/:/public
    networks:
      - nginx_nginx_net
    restart: unless-stopped
  
networks:
  nginx_nginx_net:
    external: true
